### ISSUE TITLE
Assembly not loaded correctly

### ISSUE THREAD

**Issue by MARCO-K** [Flittermelint/PSAwtrix3#1]
Beim importieren des Moduls habe ich folgenden Fehler:
Der : Die Benennung "Der" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren
Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), und
wiederholen Sie den Vorgang.
In Zeile:1 Zeichen:1
+ Der Typ [System.Drawing.Color] wurde nicht gefunden.
+ ~~~
    + CategoryInfo          : ObjectNotFound: (Der:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Es reicht aus, die assembly zu laden:
Add-Type -Assembly System.Drawing

Gruß,
Marco

**Comment by Flittermelint** [comment]
Thanks Marco, for the very first issue in my very first repo 😊

Fixed it by inserting "Add-Type -Assembly System.Drawing" at the beginning of PSAwtrix.psm1.

Classical error while using Powershell ISE for devleopment, because "System.Drawing" is loaded by default there...

Best regards
Frank
